#!/usr/bin/env python

from docutils.core import publish_cmdline, default_description
import html5css3

description = 'Generates (X)HTML5 documents from standalone reStructuredText sources.' + default_description
publish_cmdline(writer=html5css3.Writer(), description=description)